name: Custom deployment script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Process the files
      run: |
        cd ${{ github.workspace }}/entries
        find . ! -name 'mykola.html' -type f -exec rm -f {} +
        mv ./mykola.html ./index.html
        cd ..
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -m "Deployed for ${{ github.sha }}"
        git push origin `git subtree split --prefix entries master`:gh-pages --force
        git subtree push --prefix entries origin gh-pages
